import type { SavedScan } from "@/types";

/**
 * Export a scan verdict as a PDF using the browser's native print-to-PDF. Opens a
 * clean, standalone report in a new window and triggers the print dialog, where the
 * user chooses "Save as PDF". Zero external dependencies and works fully offline.
 */
export function exportScanPdf(result: SavedScan): boolean {
  const win = window.open("", "_blank", "noopener,noreferrer,width=820,height=1000");
  if (!win) return false; // popup blocked

  const esc = (s: unknown) =>
    String(s ?? "").replace(/[&<>"']/g, (c) =>
      ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" })[c] as string,
    );

  const scamPct = Math.round(result.scamProbability * 100);
  const generated = new Date().toLocaleString();
  const flags = result.flags?.length
    ? result.flags
        .map((f) => `<li><strong>${esc(f.flag)}</strong>${f.description ? ` — ${esc(f.description)}` : ""}</li>`)
        .join("")
    : "<li>No specific flags were raised.</li>";

  win.document.write(`<!doctype html>
<html><head><meta charset="utf-8"><title>Neural Shield AI — Scan Report</title>
<style>
  * { box-sizing: border-box; }
  body { font-family: -apple-system, Segoe UI, Roboto, Helvetica, Arial, sans-serif; color: #0b1020; margin: 40px; }
  h1 { font-size: 20px; margin: 0 0 2px; }
  .sub { color: #667; font-size: 12px; margin-bottom: 24px; }
  .verdict { display: inline-block; padding: 6px 14px; border-radius: 999px; font-weight: 700; font-size: 14px;
             background: #eef2ff; color: #1e3a8a; text-transform: capitalize; }
  .grid { display: flex; gap: 16px; margin: 20px 0; }
  .card { flex: 1; border: 1px solid #e5e7eb; border-radius: 12px; padding: 16px; }
  .card .k { font-size: 11px; text-transform: uppercase; letter-spacing: .08em; color: #667; }
  .card .v { font-size: 26px; font-weight: 700; margin-top: 4px; }
  h2 { font-size: 13px; text-transform: uppercase; letter-spacing: .08em; color: #667; margin: 22px 0 8px; }
  ul { margin: 0; padding-left: 18px; } li { margin: 4px 0; font-size: 13px; }
  .rec { border: 2px solid #6366f1; background: #eef2ff; border-radius: 12px; padding: 14px 16px; font-size: 14px; }
  .foot { margin-top: 32px; border-top: 1px solid #e5e7eb; padding-top: 10px; color: #99a; font-size: 11px; }
</style></head>
<body>
  <h1>Neural Shield AI — Scan Report</h1>
  <div class="sub">Generated ${esc(generated)} · Engine ${esc(result.aiModel ?? "n/a")}</div>
  <span class="verdict">${esc(result.riskLevel)}${result.scamType ? " · " + esc(result.scamType) : ""}</span>
  <div class="grid">
    <div class="card"><div class="k">Trust score</div><div class="v">${esc(result.trustScore)}/100</div></div>
    <div class="card"><div class="k">Scam probability</div><div class="v">${scamPct}%</div></div>
  </div>
  <h2>Recommendation</h2>
  <div class="rec">${esc(result.recommendation)}</div>
  ${result.detailedAnalysis ? `<h2>Analysis</h2><p style="font-size:13px">${esc(result.detailedAnalysis)}</p>` : ""}
  <h2>Detected flags</h2>
  <ul>${flags}</ul>
  <div class="foot">This report was generated by Neural Shield AI. Verdicts are advisory — always use your own judgement.</div>
  <script>window.onload = function(){ setTimeout(function(){ window.print(); }, 150); };</script>
</body></html>`);
  win.document.close();
  return true;
}
